project:
  type: website
  output-dir: docs

website:
  title: "sstew45.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - games.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



