project:
  type: website
  output-dir: docs

website:
  title: "Data Drives Discovery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - games.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



